# Generated by Django 5.2.1 on 2025-06-04 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0003_progressrecord_created_at_alter_client_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('diet_type', models.CharField(max_length=50)),
                ('total_days', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_copy', models.BooleanField(default=False, verbose_name='Kopya Program')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Beslenme Programı',
                'verbose_name_plural': 'Beslenme Programları',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal Edildi')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_plans', to='plans.nutritionprogram')),
                ('program_copy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='copied_plans', to='plans.nutritionprogram')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planlar',
            },
        ),
    ]
