# Generated by Django 5.2.1 on 2025-05-30 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0003_progressrecord_created_at_alter_client_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Program Adı')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('total_days', models.PositiveIntegerField(verbose_name='Toplam Gün')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Beslenme Programı',
                'verbose_name_plural': 'Beslenme Programları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Başlangıç Tarihi')),
                ('end_date', models.DateField(verbose_name='Bitiş Tarihi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Müşteri')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.nutritionprogram', verbose_name='Program')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planlar',
                'ordering': ['-start_date'],
            },
        ),
    ]
