# Generated by Django 5.2.1 on 2025-06-02 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Besin Adı')),
                ('calories', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Kalori (kcal/100g)')),
                ('protein', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Protein (g/100g)')),
                ('fat', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Yağ (g/100g)')),
                ('carbs', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Karbonhidrat (g/100g)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Besin',
                'verbose_name_plural': 'Besinler',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Öğün Adı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Kahvaltı'), ('lunch', 'Öğle Yemeği'), ('dinner', 'Akşam Yemeği'), ('snack', 'Ara Öğün')], max_length=20, verbose_name='Öğün Tipi')),
                ('day_number', models.PositiveIntegerField(verbose_name='Gün')),
                ('time', models.TimeField(verbose_name='Saat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='plans.nutritionprogram')),
            ],
            options={
                'verbose_name': 'Öğün',
                'verbose_name_plural': 'Öğünler',
                'ordering': ['day_number', 'time'],
                'unique_together': {('program', 'day_number', 'time')},
            },
        ),
        migrations.CreateModel(
            name='MealFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Miktar (g)')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.food', verbose_name='Besin')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_foods', to='meals.meal')),
            ],
            options={
                'verbose_name': 'Öğün Besini',
                'verbose_name_plural': 'Öğün Besinleri',
            },
        ),
    ]
