# Generated by Django 5.2.1 on 2025-05-30 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meals', '0001_initial'),
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='plans.nutritionprogram'),
        ),
        migrations.AddField(
            model_name='mealfood',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.food', verbose_name='Besin'),
        ),
        migrations.AddField(
            model_name='mealfood',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_foods', to='meals.meal'),
        ),
    ]
